
..\..\bin\os2\wdspc10.exe pas\wdspc10\wdspc10.pas ..\..\os\os2\lib ..\..\os\os2\lib share %1-$C+-M
..\..\bin\os2\wdspc10.exe pas\wdspc10\wdspc10.pas ..\..\os\os2\output ..\..\os\os2\lib %1-$C+-VDM-T2-OS2



..\..\bin\os2\wdspc10.exe pas\wdspd10\wdspd10.pas ..\..\os\os2\output ..\..\os\os2\lib share;..\..\library\source\rtl;..\..\library\source\rtl\os2;..\..\library\source\tp70;..\..\library\source\rc;..\..\library\source\spcc %1-$C+
..\..\bin\os2\wdspc10.exe rc\wdrcc10\wdrcc10.pas ..\..\os\os2\output ..\..\os\os2\lib .\share;..\..\library\source\rtl;..\..\library\source\rtl\os2;..\..\library\source\tp70;..\..\library\source\rc;..\..\library\source\spcc %1-$C+-M
..\..\bin\os2\wdspc10.exe rc\wdrcc10\wdrcc10.pas ..\..\os\os2\output ..\..\os\os2\lib .\share;..\..\library\source\rtl;..\..\library\source\rtl\os2;..\..\library\source\tp70;..\..\library\source\rc;..\..\library\source\spcc %1-$C+-T2
..\..\bin\os2\wdspc10.exe rc\wdrcd10\wdrcd10.pas ..\..\os\os2\output ..\..\os\os2\lib .\share;..\..\library\source\rtl;..\..\library\source\rtl\os2;..\..\library\source\tp70;..\..\library\source\rc;..\..\library\source\spcc %1-$C+-M
..\..\bin\os2\wdspc10.exe rc\wdrcd10\wdrcd10.pas ..\..\os\os2\output ..\..\os\os2\lib .\share;..\..\library\source\rtl;..\..\library\source\rtl\os2;..\..\library\source\tp70;..\..\library\source\rc;..\..\library\source\spcc %1-$C+
..\..\bin\os2\wdspc10.exe hlp\wdhlpd10\wdhlpd10.pas ..\..\os\os2\lib ..\..\os\os2\lib .\share;..\..\library\source\rtl;..\..\library\source\rtl\os2;..\..\library\source\tp70;..\..\library\source\rc;..\..\library\source\spcc %1-$C+-M
..\..\bin\os2\wdspc10.exe hlp\wdhlpc10\wdhlpc10.pas ..\..\os\os2\lib ..\..\os\os2\lib .\share;..\..\library\source\rtl;..\..\library\source\rtl\os2;..\..\library\source\tp70;..\..\library\source\rc;..\..\library\source\spcc %1-$C+-M
..\..\bin\os2\wdspc10.exe hlp\wdhlpc10\wdhlpc10.pas ..\..\os\os2\output ..\..\os\os2\lib .\share;..\..\library\source\rtl;..\..\library\source\rtl\os2;..\..\library\source\tp70;..\..\library\source\rc;..\..\library\source\spcc %1-$C+-T2
..\..\bin\os2\wdspc10.exe hlp\wdhlpd10\wdhlpd10.pas ..\..\os\os2\output ..\..\os\os2\lib .\share;..\..\library\source\rtl;..\..\library\source\rtl\os2;..\..\library\source\tp70;..\..\library\source\rc;..\..\library\source\spcc %1-$C+
..\..\bin\os2\wdspc10.exe wdspdb10\wdspdb10.pas ..\..\os\os2\output ..\..\os\os2\lib .\share;..\..\library\source\rtl;..\..\library\source\rtl\os2;..\..\library\source\tp70;..\..\library\source\rc;..\..\library\source\spcc;wdspdb10 %1-$C+-M
..\..\bin\os2\wdspc10.exe wdspdb10\wdspdb10.pas ..\..\os\os2\output ..\..\os\os2\lib .\share;..\..\library\source\rtl;..\..\library\source\rtl\os2;..\..\library\source\tp70;..\..\library\source\rc;..\..\library\source\spcc;wdspdb10 %1-$C+


